# Generated by Django 3.2.4 on 2021-08-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timewrite', models.DateTimeField(auto_now_add=True, verbose_name='Записано')),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('addinform', models.CharField(blank=True, max_length=500, null=True)),
                ('dt', models.CharField(blank=True, max_length=50, null=True)),
                ('d', models.CharField(blank=True, max_length=20, null=True)),
                ('url_photo', models.CharField(blank=True, max_length=100, null=True)),
                ('img', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
